### PR TITLE
Update current

### PR DESCRIPTION
**Pull request by sabinaabh**
https://www.klix.ba/vijesti/bih/koronavirus-potvrdjen-i-u-brckom-zarazene-dvije-mladje-osobe/200323054

### CODE REVIEW

**Comment by sabinaabh** [comment]
https://www.klix.ba/vijesti/bih/koronavirus-potvrdjen-i-u-brckom-zarazene-dvije-mladje-osobe/200323054

**Comment by aminaalijagic** [comment]
Latitude and longitude for Brcko should be added as well

**Review by nejra — DISMISSED** [review]
treba grad dodati

**Review by aminaalijagic — APPROVED** [review]
Grad dodan u drugom PR-u

**Pull request merged**
